cc_test(
    name = "fcgi_si_test",
    deps =
        ["//:fcgi_si",
        "@googletest//:gtest",
        "@googletest//:gtest_main"],
    srcs = ["//test:fcgi_si_test.cc"],
    timeout = "long"
)
