# MIT License
#
# Copyright (c) 2021 Adam J. Breland
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

local_repository(
    name = "as_components",
    path = "external_repo_links/as_components"
)

local_repository(
    name = "simple_bazel_cpp_toolchain",
    path = "external_repo_links/simple_bazel_cpp_toolchain"
)

local_repository(
    name = "as_components_testing",
    path = "external_repo_links/as_components_testing"
)

local_repository(
    name = "googletest",
    path = "external_repo_links/googletest"
)

local_repository(
    name = "id_manager",
    path = "external_repo_links/id_manager"
)

local_repository(
    name = "socket_functions",
    path = "external_repo_links/socket_functions"
)

register_execution_platforms(
    "@local_config_platform//:host",
    "@simple_bazel_cpp_toolchain//:simple_cpp_x86_64_linux_platform"
)

register_toolchains(
    "@simple_bazel_cpp_toolchain//:simple_x86_64_linux_toolchain"
)
