local_repository(
    name = "a_component_testing",
    path = "external/a_component_testing"
)

local_repository(
    name = "googletest",
    path = "external/googletest"
)

local_repository(
    name = "id_manager",
    path = "external/id_manager"
)

local_repository(
    name = "socket_functions",
    path = "external/socket_functions"
)
