cc_library(
  name       = "as_components_testing_utilities",
  srcs       = [
      "//:src/as_components_testing_utilities.cc",
      "//:include/as_components_testing_utilities_templates.h"
  ],
  hdrs       = ["//:include/as_components_testing_utilities.h"],
  copts      = [
      "-std=c++17",
      "-g",
      "-O2",
      "-Wextra",
      "-iquote ."
  ],
  visibility = ["//visibility:public"]
)
