cc_test(
    name  = "socket_functions_test",
    deps  = [
             "//:socket_functions",
             "@googletest//:gtest",
             "@googletest//:gtest_main"
    ],
    srcs  = ["//test:socket_functions_test.cc"],
    copts      = [
        "-std=c++17",
        "-g",
        "-iquote .",
        "-Wextra"
    ],
)
