cc_library(
    name       = "socket_functions",
    srcs       = ["//:src/socket_functions.cc"],
    hdrs       = ["//:include/socket_functions.h"],
    copts      = [
        "-std=c++17",
        "-g",
        "-O2",
        "-Wextra"
    ],
    visibility = ["//visibility:public"]
)
